
[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[scrolling]
history = 100000
multiplier = 5

[window]
padding.x = 12
padding.y = 12
decorations = "None"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[colors.primary]
background = "0x10100E"
foreground = "0xC6C6C4"

[colors.normal]
black = "0x10100E"
blue = "0x0087BD"
cyan = "0x20B2AA"
green = "0x009F6B"
magenta = "0x9A4EAE"
red = "0xC40233"
white = "0xC6C6C4"
yellow = "0xFFD700"

[colors.bright]
black = "0x696969"
blue = "0x007FFF"
cyan = "0x00CCCC"
green = "0x03C03C"
magenta = "0xFF1493"
red = "0xFF2400"
white = "0xFFFAFA"
yellow = "0xFDFF00"
